language: go
go:
  - "1.13.x"
install: true
deploy:
  provider: releases
  api_key:
    secure: dhMF/IsPIjeu2/+YxDVwdmpVH25/wry7KC5Il6gziXvsRoBchjKOX7AxGLgAdDzg5o813fbX9Z71bN1MHh9+X3lMO69zsEwV5Hmcdfqo827K/ZsHR6QCU7Ec5ag4H7Z2BVOe41Z4nvUy6XFYsOpnb17qA/XJNeTYJ8eKnhnQuuD8yL95espVd8gx9/sal/n7dNXjKsO414YjRlCbhACPtc2uwPnWNJZwdeXgHWMn0LwaWQkDrnE8Q3Rlz/A7LVfvNdd8es64rUu4Ok6jBZv6IBk+kYps0xlhaj9lXdi/j+rAd5UEiDX5sOWqzfhV5lMxLCYurffGew9/9QSReth+j8e7Z2vCIIAIc03GYXTA+VCV17ZyEFCh/a2e2Ecd9v7hsX0hvUV4riWEFmNPkEtZXH4N5CJOni3ZrB/IO/YGAw6b6zhGgncaleqD/1lAdgmVS5WHc+2h3+qL3K4Gfzk0TVPCnRZfXJJ3dmnymO7FkNjtGfjS+1q7QKQ/fBGjxJsTCstcgS9Z3Nk/Jg5+175MtSilGJB2bkhdp9BZLsJMbQgv5SeITL6EfWmF2kaunKQ9WWhZ+cr1LpUpv6QLghz34yn2h4Ad6rqHrOv4hQSyk+scg726q4FCa3Uqu6EcKNSZzUeMkCksS9ieg0wt/5e4VlU9O1F2V5U26Cb3QYhbA4c=
  skip_cleanup: true
  file:
    - packer-post-processor-ami-copy-darwin-amd64
    - packer-post-processor-ami-copy-linux-amd64
    - packer-post-processor-ami-copy-windows-amd64.exe
  on:
    repo: alvsanand/packer-post-processor-ami-copy
    all_branches: true
    tags: true
notifications:
  email: true
